<?php 
get_header();
get_template_part('templates/intro-banner');
get_template_part('templates/intro-description');
get_template_part('templates/intro-about');
get_template_part('templates/intro-testimonials');
get_template_part('templates/intro-services');
get_template_part('templates/intro-promotion');
get_footer() 
?>